apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
  labels:
    app: {{ .Values.serviceName }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.sshPort }}
      protocol: TCP
      name: ssh
    - port: {{ .Values.global.port }}
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.serviceName }}
