apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.OpenNMS.minion.serviceName }}
  labels:
    app: {{ .Values.OpenNMS.minion.serviceName }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.OpenNMS.minion.serviceName }}
  replicas: {{ .Values.OpenNMS.minion.replicas }}
  template:
    metadata:
      labels:
        appdomain: opennms
        app: {{ .Values.OpenNMS.minion.serviceName }}
      annotations:
        linkerd.io/inject: enabled
        kubectl.kubernetes.io/default-container: "{{ .Values.OpenNMS.minion.serviceName }}"
    spec:
      serviceAccountName: {{ .Values.OpenNMS.minion.serviceName }}-sa
      {{- if .Values.nodeRestrictions.enabled }}
      nodeSelector:                                                                                    
        {{ .Values.nodeRestrictions.key }}: {{ .Values.nodeRestrictions.value }}                       
      tolerations:
        - effect: "NoSchedule"                                                                         
          key: "{{ .Values.nodeRestrictions.key }}"                                                    
          operator: "Equal"
          value: {{ .Values.nodeRestrictions.value }} 
      affinity: 
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:                                             
          - weight: 1                                                                                  
            preference:                                                                                
              matchExpressions:                                                                        
              - key: "{{ .Values.nodeRestrictions.key }}"                                              
                operator: In
                values:                                                                                
                - {{ .Values.nodeRestrictions.value }}                                                 
      {{- end }}
      volumes:
        - name: minion-secrets
          secret:
            defaultMode: 420
            secretName: minion-app-secrets
        {{- if .Values.OpenNMS.minion.extraVolumes }}
          {{ toYaml .Values.OpenNMS.minion.extraVolumes | nindent 8 }}
        {{- end }}
      initContainers:
        {{- if eq (include "onOpenShift" .) "false" }}
        - name: init-sysctl
          image: busybox
          command:
            - sysctl
            - -w
            - net.ipv4.ping_group_range=0 429496729
          securityContext:
            privileged: true
        {{- end }}
        {{- if .Values.OpenNMS.minion.extraInitContainers }}
          {{ toYaml .Values.OpenNMS.minion.extraInitContainers | nindent 8 }}
        {{- end }}
      containers:
        - name: {{ .Values.OpenNMS.minion.serviceName }}
          image: {{ include "lokahi.image" (dict "Values" .Values "thisService" .Values.OpenNMS.minion) | quote }}
          imagePullPolicy: {{ .Values.OpenNMS.minion.imagePullPolicy }}
          env:
            {{- if .Values.OpenNMS.minion.id }}
            - name: MINION_ID
              value: "{{ .Values.OpenNMS.minion.id }}"
            {{- end }}
            - name: GRPC_CLIENT_KEYSTORE_PASSWORD
              value: "{{ .Values.OpenNMS.minion.grpcClientKeystorePassword }}"
            - name: MINION_GATEWAY_HOST
            {{- if .Values.OpenNMS.minion.gatewayHost }}
              value: "{{ .Values.OpenNMS.minion.gatewayHost }}" # we're inside the cluster, so we need to talk to the internal service name
            {{- else }}
              value: "minion.{{ .Values.hostname }}" 
            {{- end}}
            - name: GRPC_CLIENT_OVERRIDE_AUTHORITY
              value: "minion.{{ .Values.hostname }}" # but the TLS certificate will have the external name, so expect that
            {{- if .Values.OpenNMS.minion.customCertificateAuthority }}
            - name: GRPC_CLIENT_TRUSTSTORE
              value: "/opt/karaf/certs/CA.cert"
            {{- end}}
            - name: JAVA_TOOL_OPTIONS
              value: "-Djava.net.preferIPv4Stack=true -XX:MaxRAMPercentage=50 -javaagent:agent/opentelemetry-javaagent.jar -agentlib:jdwp=transport=dt_socket,server=y,address=5005,suspend=n,quiet=y" # FIXME: Permanent debug port, enable only for dev mode
            {{- if .Values.OpenNMS.minion.logLevel }}
            - name: KARAF_OPTS
              value: -Dkaraf.log.console={{ .Values.OpenNMS.minion.logLevel }}
            {{- end }}
            {{- if .Values.OpenNMS.global.openTelemetry.otlpTracesEndpoint }}
            - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
              value: {{ .Values.OpenNMS.global.openTelemetry.otlpTracesEndpoint | toYaml }}
            {{- else }}
            - name: OTEL_TRACES_EXPORTER
              value: "none"
            {{- end }}
            - name: OTEL_METRICS_EXPORTER
              value: "none"
            {{- if .Values.OpenNMS.global.openTelemetry.env }}
              {{- range $key, $val := .Values.OpenNMS.global.openTelemetry.env }}
            - name: {{ $key }}
              value: {{ $val | quote }}
              {{- end }}
            {{- end }}
            # Do not put any env variables below this. The lokahi.development.env include should be last
            # in the 'env' section so variables can be overridden with Helm chart values when needed.
            {{- include "lokahi.deployment.env" (dict "Values" .Values "thisService" .Values.OpenNMS.minion) | nindent 12 }}
          ports:
            - name: http
              containerPort: {{ .Values.OpenNMS.minion.port }}
            - name: snmp-traps
              protocol: UDP
              containerPort: {{ .Values.OpenNMS.minion.trapsListenerPort }}
            - name: ssh
              containerPort: {{ .Values.OpenNMS.minion.sshPort }}
            - name: netflow5
              protocol: UDP
              containerPort: {{ .Values.OpenNMS.minion.netflow5ListenerPort }}
            - name: netflow9
              protocol: UDP
              containerPort: {{ .Values.OpenNMS.minion.netflow9ListenerPort }}
          volumeMounts:
            - name: minion-secrets
              subPath: "minion.p12"
              mountPath: "/opt/karaf/minion.p12"
            {{- if .Values.OpenNMS.minion.customCertificateAuthority }}
            - name: minion-secrets
              subPath: "CA.cert"
              mountPath: "/opt/karaf/certs/CA.cert"
            {{- end}}
            {{- if .Values.OpenNMS.minion.extraMounts }}
              {{ toYaml .Values.OpenNMS.minion.extraMounts | nindent 12 }}
            {{- end }}
          resources:
            limits:
              cpu: "{{ .Values.OpenNMS.minion.resources.limits.cpu }}"
              memory: "{{ .Values.OpenNMS.minion.resources.limits.memory }}"
            requests:
              cpu: "{{ .Values.OpenNMS.minion.resources.requests.cpu }}"
              memory: "{{ .Values.OpenNMS.minion.resources.requests.memory }}"
          startupProbe:
            exec:
              command:
              - sh
              - -c
              - unset JAVA_TOOL_OPTIONS; echo "opennms:task-set-print" | bin/client -b | grep -q taskDefinition
            initialDelaySeconds: 25
            periodSeconds: 5
            failureThreshold: 10
