apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: minion-app-secrets
data: # 
  minion.p12: |-
     {{ .Files.Get "certs/minion1.p12" | b64enc }}
  CA.cert: |-
     {{ .Files.Get "certs/ca.crt" | b64enc }}