{{- if not .Values.OpenNMS.inventory.inventorySecret  }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.OpenNMS.inventory.serviceName }}-encryption-key
  namespace: {{ .Release.Namespace }}
data:
  {{- $secretData := get (lookup "v1" "Secret" .Release.Namespace (print .Values.OpenNMS.inventory.serviceName "-encryption-key")) "data" | default dict }}
  encryptionKey: "{{ (get $secretData "encryptionKey" | b64dec) | default .Values.OpenNMS.inventory.encryptionKey | default (randAscii 32) | b64enc }}"
type: Opaque
{{- end }}