apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-boot-app-config
  namespace: {{ .Release.Namespace }}
data:
  logback-spring.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <configuration>
        <include resource="org/springframework/boot/logging/logback/defaults.xml"/>
    
        <springProfile name="json-logging">
            <appender name="CONSOLE" class="ch.qos.logback.core.ConsoleAppender">
                <encoder class="ch.qos.logback.core.encoder.LayoutWrappingEncoder">
                    <layout class="ch.qos.logback.contrib.json.classic.JsonLayout">
                        <jsonFormatter class="ch.qos.logback.contrib.jackson.JacksonJsonFormatter">
                            <prettyPrint>${CONSOLE_JSON_PRETTY:-false}</prettyPrint>
                        </jsonFormatter>
                        <timestampFormat>yyyy-MM-dd'T'HH:mm:ss.SSSX</timestampFormat>
                        <timestampFormatTimezoneId>UTC</timestampFormatTimezoneId>
                        <appendLineSeparator>true</appendLineSeparator>
                    </layout>
                </encoder>
            </appender>
        </springProfile>
    
        <springProfile name="!json-logging">
            <include resource="org/springframework/boot/logging/logback/console-appender.xml"/>
        </springProfile>
    
        <root level="INFO">
            <appender-ref ref="CONSOLE"/>
        </root>
    </configuration>
  application-json-logging.properties: |
    spring.main.banner-mode=off
