apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-boot-env
  namespace: {{ .Release.Namespace }}
data:
{{- if .Values.global.enableJsonLogging }}
  SPRING_PROFILES_INCLUDE: default,json-logging
{{- end }}
{{- with .Values.global.springBoot }}
  {{- range $key, $val := .env }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
{{- end }}
{{- if  not (eq (include "lokahi.openTelemetry" (dict "thisService" .Values.global.openTelemetry.otlpTracesEndpoint)) "null") }}
  OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: {{ include "lokahi.openTelemetry" (dict "thisService" .Values.global.openTelemetry.otlpTracesEndpoint) }}
{{- else }}
  OTEL_TRACES_EXPORTER: "none"
{{- end }}
  OTEL_METRICS_EXPORTER: "none"
  OTEL_PROPAGATORS: {{ include "lokahi.openTelemetry" (dict "thisService" .Values.global.openTelemetry.env.OTEL_PROPAGATORS)}}

