apiVersion: v2
name: lokahi
version: 1.0.1
home: https://github.com/OpenNMS-Cloud/lokahi
icon: https://www.opennms.com/wp-content/uploads/2021/04/OpenNMS_Favicon_36px.png
type: application
description: A Helm chart for running OpenNMS Lokahi in Kubernetes
appVersion: "v0.0.61"

dependencies:
  - name: "Citus"
    version: "12.1-alpine"
    repository: "file://../dependencies/citus"
    condition: Citus.enabled
  - name: "Cortex"
    version: "1.14.0"
    repository: "file://../dependencies/cortex"
    condition: Cortex.enabled
  - name: "Grafana"
    version: "0.0.60"
    repository: "file://../dependencies/grafana"
    condition: Grafana.enabled
  - name: "Kafka"
    version: "3.3.2"
    repository: "file://../dependencies/kafka"
    condition: Kafka.enabled
  - name: "Keycloak"
    version: "0.0.60"
    repository: "file://../dependencies/keycloak"
    condition: Keycloak.enabled
  - name: "Prometheus"
    version: "2.39.1"
    repository: "file://../dependencies/prometheus"
    condition: Prometheus.enabled

maintainers:
  - name: The OpenNMS Group Inc.
    url: https://www.opennms.com
