apiVersion: v2
name: lokahi
version: 1.0.0-alpha
home: https://github.com/OpenNMS-Cloud/lokahi
icon: https://www.opennms.com/wp-content/uploads/2021/04/OpenNMS_Favicon_36px.png
type: application
description: A Helm chart for running OpenNMS Lokahi in Kubernetes
appVersion: "v1.0.0"

maintainers:
  - name: The OpenNMS Group Inc.
    url: https://www.opennms.com