apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.OpenNMS.ui.serviceName }}
  name: {{ .Values.OpenNMS.ui.serviceName }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: {{ .Values.OpenNMS.port.http | default .Values.OpenNMS.ui.port }}
      protocol: TCP
      targetPort: {{ .Values.OpenNMS.ui.port }}
      name: http
  selector:
    app: {{ .Values.OpenNMS.ui.serviceName }}
  type: NodePort
