enabled: true # to disable prometheus change it to false
path: /prometheus # prometheus endpoint
serviceName: prometheus
port: 9090
image: prom/prometheus:v2.39.1
imagePullPolicy: IfNotPresent
replicas: 1
resources:
  limits:
    cpu: "1"
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 100Mi
auth:
  username: "admin"
  password: "notset"
  secretName: "prometheus-credentials"
  externalSecret: ""

nodeRestrictions: # will be applied to every pod in the instance
  enabled: false
  key: kubernetes.azure.com/scalesetpriority
  value: spot
