{{- if .Values.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: postgres
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.serviceName }}
stringData:
  password: "{{ .Values.global.citus.adminPassword | default .Values.adminPassword }}"

  adminUser: "postgres"
  adminPwd: "{{ .Values.adminPassword }}"
  keycloakUser: "keycloak"
  keycloakPwd: "{{ .Values.keycloakPassword }}"
  inventoryUser: "inventory"
  inventoryPwd: "{{ .Values.inventoryPassword }}"
  alertUser: "alert"
  alertPwd: "{{ .Values.alertPassword }}"
  notificationUser: "notification"
  notificationPwd: "{{ .Values.notificationPassword }}"
  grafanaUser: "grafana"
  grafanaPwd: "{{ .Values.grafanaPassword }}"
  eventsUser: "events"
  eventsPwd: "{{ .Values.eventsPassword }}"
  dataChoicesUsr: "datachoices"
  dataChoicesPwd: "{{ .Values.dataChoicesPassword }}"
  minionGatewayUsr: "minion_gateway"
  minionGatewayPwd: "{{ .Values.minionGatewayPassword }}"
type: Opaque
{{- end }}

