{{- if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: citus
spec:
  selector:
    app: citus
  clusterIP: None
  ports:
  - port: {{ .Values.global.citus.port | default .Values.port }}
    targetPort: {{ .Values.global.citus.port | default .Values.port }}
    name: postgres
{{- end }}
