apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-access-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: default1
  namespace: default
roleRef:
  kind: Role
  name: secret-creator-role
  apiGroup: rbac.authorization.k8s.io