apiVersion: v1
kind: ServiceAccount
metadata:
  name: default1
  namespace: default
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: lokahi
    meta.helm.sh/release-namespace: default