apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-creator-role
  namespace: default
rules:
- apiGroups: [""]
  resources: ["secrets", "configmaps"]
  verbs: ["create", "get", "list"] 
