{{- if .Values.enabled }}
apiVersion: v1
kind: Secret # Currently stores passwords!
metadata:
  labels:
    app: {{ .Values.serviceName }}
  name: citus-initial-sql
  namespace: {{ .Release.Namespace }}
stringData:
  postgres.initial.script.sql: |

    DO $$ BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '{{ .Values.global.citus.databaseName | default .Values.databaseName }}') THEN
            CREATE ROLE {{ .Values.global.citus.databaseName | default .Values.databaseName }} WITH LOGIN PASSWORD '{{ .Values.global.citus.adminPassword | default .Values.adminPassword }}';
        END IF;
    END $$;

    CREATE USER grafana with password '{{ .Values.grafanaPassword }}';
    CREATE DATABASE grafana;
    GRANT ALL ON DATABASE grafana TO grafana;
    \connect grafana
    GRANT ALL ON SCHEMA public TO grafana;

    \connect {{ .Values.global.citus.databaseName | default .Values.databaseName }}
    CREATE USER opennms with password '{{ .Values.openNMSPassword }}';
    GRANT ALL ON DATABASE {{ .Values.global.citus.databaseName | default .Values.databaseName }} TO opennms;

    \connect {{ .Values.global.citus.databaseName | default .Values.databaseName }};

    CREATE USER keycloak with password '{{ .Values.keycloakPassword }}';
    CREATE SCHEMA IF NOT EXISTS keycloak AUTHORIZATION keycloak;

    CREATE USER inventory with password '{{ .Values.inventoryPassword }}';
    CREATE SCHEMA IF NOT EXISTS inventory AUTHORIZATION inventory;

    CREATE USER alert with password '{{ .Values.alertPassword }}';
    CREATE SCHEMA IF NOT EXISTS alert AUTHORIZATION alert;

    CREATE USER notification with password '{{ .Values.notificationPassword }}';
    CREATE SCHEMA IF NOT EXISTS notification AUTHORIZATION notification;

    CREATE USER events with password '{{ .Values.eventsPassword }}';
    CREATE SCHEMA IF NOT EXISTS events AUTHORIZATION events;

    CREATE USER datachoices with password '{{ .Values.dataChoicesPassword }}';
    CREATE SCHEMA IF NOT EXISTS datachoices AUTHORIZATION datachoices;

    CREATE USER minion_gateway with password '{{ .Values.minionGatewayPassword }}';
    CREATE SCHEMA IF NOT EXISTS minion_gateway AUTHORIZATION minion_gateway;

type: Opaque
{{- end }}
