{{- if .Values.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.serviceName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.serviceName }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-5"
data:
  password: UEBzc3dvcmQxMjM=
{{- if eq .Values.adminPassword "notset" }}
  adminUser: '{{ "postgres" | b64enc }}' 
  adminPwd: '{{ include "lokahi.passwords.admin" . | b64enc }}'
{{- else }}
  adminUser: '{{ "postgres" | b64enc }}'
  adminPwd: "{{ .Values.adminPassword | b64enc }}"
{{- end }}

{{- if eq .Values.keycloakPassword "notset" }}
  keycloakUser: '{{ "keycloak" | b64enc }}'
  keycloakPwd: '{{ include "lokahi.passwords.keycloak" . | b64enc }}'
{{- else }}
  keycloakUser: '{{ "keycloak" | b64enc }}'
  keycloakPwd: "{{ .Values.keycloakPassword | b64enc }}"
{{- end }}

{{- if eq .Values.inventoryPassword "notset" }}
  inventoryUser: '{{ "inventory" | b64enc }}'
  inventoryPwd: '{{ include "lokahi.passwords.inventory" . | b64enc }}'
{{- else }}
  inventoryUser: '{{ "inventory" | b64enc }}'
  inventoryPwd: "{{ .Values.inventoryPassword | b64enc }}"
{{- end }}

{{- if eq .Values.alertPassword "notset" }}
  alertUser: '{{ "alert" | b64enc }}'
  alertPwd: '{{ include "lokahi.passwords.alert" . | b64enc }}'
{{- else }}
  alertUser: '{{ "alert" | b64enc }}'
  alertPwd: "{{ .Values.alertPassword | b64enc }}"
{{- end }}

{{- if eq .Values.notificationPassword "notset" }}
  notificationUser: '{{ "notification" | b64enc }}'
  notificationPwd: '{{ include "lokahi.passwords.notification" . | b64enc }}'
{{- else }}
  notificationUser: '{{ "notification" | b64enc }}'
  notificationPwd: "{{ .Values.notificationPassword | b64enc }}"
{{- end }}

{{- if eq .Values.grafanaPassword "notset" }}
  grafanaUser: '{{ "grafana" | b64enc }}'
  grafanaPwd: '{{ include "lokahi.passwords.grafana" . | b64enc }}'
{{- else }}
  grafanaUser: '{{ "grafana" | b64enc }}'
  grafanaPwd: "{{ .Values.grafanaPassword | b64enc }}"
{{- end }}

{{- if eq .Values.eventsPassword "notset" }}
  eventsUser: '{{ "events" | b64enc }}'
  eventsPwd: '{{ include "lokahi.passwords.events" . | b64enc }}'
{{- else }}
  eventsUser: '{{ "events" | b64enc }}'
  eventsPwd: "{{ .Values.eventsPassword | b64enc }}"
{{- end }}

{{- if eq .Values.dataChoicesPassword "notset" }}
  dataChoicesUsr: '{{ "datachoices" | b64enc }}'
  dataChoicesPwd: '{{ include "lokahi.passwords.datachoices" . | b64enc }}'
{{- else }}
  dataChoicesUsr: '{{ "datachoices" | b64enc }}'
  dataChoicesPwd: "{{ .Values.dataChoicesPassword | b64enc }}"
{{- end }}

{{- if eq .Values.minionGatewayPassword "notset" }}
  minionGatewayUsr: '{{ "minion_gateway" | b64enc }}'
  minionGatewayPwd: '{{ include "lokahi.passwords.minionGateway" . | b64enc }}'
{{- else }}
  minionGatewayUsr: '{{ "minion_gateway" | b64enc }}'
  minionGatewayPwd: "{{ .Values.minionGatewayPassword | b64enc }}"
{{- end }}
type: Opaque
{{- end }}