{{- if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: citus-worker
  namespace: {{ .Release.Namespace }}
  labels:
    app: citus-worker
spec:
  selector:
    app: citus-worker
  clusterIP: None
  ports:
  - port: {{ .Values.global.citus.port | default .Values.port }}
    targetPort: 5432
    name: postgres
{{- end }}
