apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tls-secret-binding
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: tls-secret-role
  apiGroup: rbac.authorization.k8s.io