apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: opennms-ca-issuer
  namespace: {{ .Release.Namespace }}
spec:
  ca:
    secretName: root-ca-certificate
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: opennms-ui-certificate
  namespace: {{ .Release.Namespace }}
spec:
  secretName: opennms-ui-certificate
  duration: {{ .Values.certSigned.duration}}h
  renewBefore: {{ .Values.certSigned.renewBefore}}h
  isCA: false
  commonName: {{ .Values.caCert.commonName }} 
  dnsNames:
    - {{ .Values.hostname }} 
  issuerRef:
    name: opennms-ca-issuer
    kind: Issuer

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: opennms-minion-gateway-certificate
  namespace: {{ .Release.Namespace }}
spec:
  secretName: opennms-minion-gateway-certificate
  duration: {{ .Values.certSigned.duration}}h
  renewBefore: {{ .Values.certSigned.renewBefore}}h
  isCA: false
  commonName: {{ .Values.caCert.commonName }}
  dnsNames:
    - minion.{{ .Values.hostname }}
  issuerRef:
    name: opennms-ca-issuer
    kind: Issuer