{{- if .Values.OpenNMS.metricsthresholdprocessor.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.OpenNMS.metricsthresholdprocessor.serviceName }}
  labels:
    app: {{ .Values.OpenNMS.metricsthresholdprocessor.serviceName }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.OpenNMS.port.http | default 8080 }}
      protocol: TCP
      targetPort: 8080
      name: http
    - port: {{ .Values.OpenNMS.port.grpc | default 6565 }}
      protocol: TCP
      targetPort: 6565
      name: grpc
  selector:
    app: {{ .Values.OpenNMS.metricsthresholdprocessor.serviceName }}
{{- end }}