{{- if not .Values.auth.externalSecret  }}
{{- $user := required "Prometheus.auth.username required" .Values.auth.username }}
{{- $pass := required "Prometheus.auth.password required" .Values.auth.password }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.auth.secretName }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  auth: {{ htpasswd $user $pass | b64enc }}
{{- end }}
