{{- if .Values.prometheus.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.prometheus.serviceName }}
  labels:
    app: {{ .Values.prometheus.serviceName }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.prometheus.serviceName }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.prometheus.serviceName }}-sa
    namespace: default
{{- end }}