{{- if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.serviceName }}
  name: {{ .Values.serviceName }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.port }}
      targetPort: 9090
      protocol: TCP
      name: prometheus-http
  selector:
    app: {{ .Values.serviceName }}
{{- end }}
