{{- if .Values.ingress.defaultEndpointsEnabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: opennms-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- range $Annotation, $Value := .Values.OpenNMS.ui.ingressAnnotations }}
    {{ $Annotation | quote }}: {{ $Value | quote }}
    {{- end }}
spec:
  ingressClassName: nginx
  defaultBackend:
    service:
      name: {{ .Values.OpenNMS.ui.serviceName }}
      port:
        number: {{ .Values.OpenNMS.port.http | default .Values.OpenNMS.ui.port }}
  rules:
    - host: {{ .Values.global.hostname }}
      http:
        paths:
          - path: {{ .Values.OpenNMS.ui.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.OpenNMS.ui.serviceName }}
                port:
                  number: {{ .Values.OpenNMS.port.http | default .Values.OpenNMS.ui.port }}
          - path: {{ .Values.Keycloak.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.Keycloak.serviceName }}
                port:
                  number: {{ .Values.global.keycloak.port | default .Values.Keycloak.port }}
          - path: {{ .Values.OpenNMS.api.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.OpenNMS.api.serviceName }}
                port:
                  number: {{ .Values.OpenNMS.port.grpc | default 9090 }}
          - path: {{ .Values.Grafana.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.Grafana.serviceName }}
                port:
                  number: {{ .Values.global.grafana.port | default .Values.Grafana.port }}
  {{- if .Values.tls.enabled }}
  tls:
    - hosts:
        -  {{.Values.global.hostname }}
      secretName: {{ .Values.OpenNMS.ui.tlsSecretName }}
  {{- end }}
{{- end }}
