{{ if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: keycloak
  name: {{ .Values.serviceName }}
  namespace: {{ .Release.Namespace }}
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - port: {{ .Values.global.keycloakPort | default .Values.port }}
      name: http
      protocol: TCP
      targetPort: 8080
    - port: {{  .Values.httpsPort  }}
      name: https
      protocol: TCP
      targetPort: 8443
    - port: 7800
      name: discovery
      protocol: TCP
      targetPort: 7800
  selector:
    app: {{ .Values.serviceName }}
  sessionAffinity: None
  type: ClusterIP
{{- end }}
