{{- if not .Values.keycloak.keycloakSecret  }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.keycloak.serviceName }}-initial-admin
  namespace: {{ .Release.Namespace }}
data:
  {{- $secretData := get (lookup "v1" "Secret" .Release.Namespace (print .Values.keycloak.serviceName "-initial-admin")) "data" | default dict }}
  username: "{{ (get $secretData "username" | b64dec) | default .Values.keycloak.adminUsername | b64enc }}"
  password: "{{ (get $secretData "password" | b64dec) | default .Values.keycloak.adminPassword | default (randAscii 32) | b64enc }}"
type: Opaque
{{- end }}