apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.keycloak.serviceName }}
  labels:
    app: keycloak
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.keycloak.serviceName }}
  replicas: {{ .Values.keycloak.replicas }}
  template:
    metadata:
      labels:
        appdomain: opennms
        app: {{ .Values.keycloak.serviceName }}
      annotations:
        kubectl.kubernetes.io/default-container: "keycloak"
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/auth/metrics"
    spec:
      {{- if .Values.nodeRestrictions.enabled }}
      nodeSelector:
        {{ .Values.nodeRestrictions.key }}: {{ .Values.nodeRestrictions.value }}
      tolerations:
        - effect: "NoSchedule"
          key: "{{ .Values.nodeRestrictions.key }}"
          operator: "Equal"
          value: {{ .Values.nodeRestrictions.value }}
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: "{{ .Values.nodeRestrictions.key }}"
                operator: In
                values:
                - {{ .Values.nodeRestrictions.value }}
      {{- end }}
      {{- if .Values.citus.enabled }}
      initContainers:
        - name: wait-for-db
          image: postgres:16-alpine
          args:
          - /bin/sh
          - -c
          - | 
            set -x;
            while ! psql -U {{ .Values.citus.adminUser }} -h postgres -c 'select 1'; do
              echo "Waiting for DB to be available"
              sleep 10
            done
            echo "Database is available"
      {{- end }}
      containers:
        - name: keycloak
          image: {{ include "lokahi.image" (dict "Values" .Values "thisService" .Values.keycloak) | quote }}
          imagePullPolicy: "{{ .Values.keycloak.imagePullPolicy }}"
          resources:
            limits:
              cpu: "{{ .Values.keycloak.resources.limits.cpu }}"
              memory: "{{ .Values.keycloak.resources.limits.memory }}"
            requests:
              cpu: "{{ .Values.keycloak.resources.requests.cpu }}"
              memory: "{{ .Values.keycloak.resources.requests.memory }}"
          args:
            - --import-realm
            {{- if .Values.OpenNMS.global.enableJsonLogging }}
            - --log-console-output=json
            {{- end }}
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-javaagent:/opt/keycloak/agent/opentelemetry-javaagent.jar"
            - name: KC_CACHE_STACK
              value: kubernetes
            - name: KC_CACHE
              value: ispn
            - name: KC_HOSTNAME_URL # Required in prod-mod to terminate TLS at Ingress
            {{- if .Values.keycloak.hostnamePort }}
              value: "{{ .Values.protocol }}://{{ .Values.hostname }}:{{ .Values.keycloak.hostnamePort }}{{ .Values.keycloak.path }}"
            {{- else }}
              value: "{{ .Values.protocol }}://{{ .Values.hostname }}{{ .Values.keycloak.path }}"
            {{- end }}
            {{- if .Values.keycloak.hostnameAdminUrl }}
            - name: KC_HOSTNAME_ADMIN_URL
              value: "{{ .Values.keycloak.hostnameAdminUrl }}"
            {{- end }}
            - name: KC_DB_URL
              value: "jdbc:postgresql://{{ .Values.keycloak.databaseHost }}:5432/{{ .Values.keycloak.databaseName }}?currentSchema={{ .Values.keycloak.databaseSchemaName }}"
            - name: KC_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: keycloakUser
            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: keycloakPwd
            - name: KEYCLOAK_ADMIN
              valueFrom:
                secretKeyRef:
                  key: username
                  name: {{ .Values.keycloak.serviceName }}-initial-admin
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: {{ .Values.keycloak.serviceName }}-initial-admin
            - name: KC_HOSTNAME_STRICT_BACKCHANNEL
              value: "false"
            - name: KC_HTTP_ENABLED
              value: "true"
            - name: KC_HTTP_RELATIVE_PATH
              value: "{{ .Values.keycloak.path }}"
            - name: KC_PROXY
              value: edge # Required in prod-mod to terminate TLS at Ingress
            - name: jgroups.dns.query
              value: "{{ .Values.keycloak.serviceName }}.{{ .Release.Namespace }}"
            {{- if and .Values.tls.enabled .Values.keycloak.tlsSecretName }}
            - name: KC_HTTPS_CERTIFICATE_FILE
              value: "/mnt/certificates/tls.crt"
            - name: KC_HTTPS_CERTIFICATE_KEY_FILE
              value: "/mnt/certificates/tls.key"
            {{- end }}
            {{- if eq (include "onOpenShift" .) "true" }}
            - name: KC_HOSTNAME_STRICT_HTTPS
              value: "false"
            {{- end }}
            {{- range $Variable, $Value := .Values.keycloak.environment }}
            - name: {{ $Variable | quote }}
              value: {{ $Value | quote }}
            {{- end }}
            {{- if .Values.OpenNMS.global.openTelemetry.otlpTracesEndpoint }}
            - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
              value: {{ .Values.OpenNMS.global.openTelemetry.otlpTracesEndpoint | toYaml }}
            {{- else }}
            - name: OTEL_TRACES_EXPORTER
              value: "none"
            {{- end }}
            - name: OTEL_METRICS_EXPORTER
              value: "none"
            {{- if .Values.OpenNMS.global.openTelemetry.env }}
              {{- range $key, $val := .Values.OpenNMS.global.openTelemetry.env }}
            - name: {{ $key }}
              value: {{ $val | quote }}
              {{- end }}
            {{- end }}
            # Do not put any env variables below this. The lokahi.development.env include should be last
            # in the 'env' section so variables can be overridden with Helm chart values when needed.
            {{- include "lokahi.deployment.env" (dict "Values" .Values "thisService" .Values.keycloak) | nindent 12 }}
          ports:
            - name: http
              containerPort: {{ .Values.keycloak.port }}
            - name: https
              containerPort: {{ .Values.keycloak.httpsPort }}
          volumeMounts:
            {{- if and .Values.tls.enabled .Values.keycloak.tlsSecretName }}
            - mountPath: /mnt/certificates
              name: keycloak-tls-certificates
            {{- end }}
            - mountPath: /opt/keycloak/data/import
              name: realm-config
          #startupProbe:
          #  httpGet:
          #    {{- if and .Values.tls.enabled .Values.keycloak.tlsSecretName }}
          #    scheme: HTTPS
          #    port: https
          #    {{- else }}
          #    scheme: HTTP
          #    port: http
          #    {{- end }}
          #    path: {{ .Values.keycloak.path }}/health/live
          #  failureThreshold: 150
          #  periodSeconds: 5
          livenessProbe:
            httpGet:
              {{- if and .Values.tls.enabled .Values.keycloak.tlsSecretName }}
              scheme: HTTPS
              port: https
              {{- else }}
              scheme: HTTP
              port: http
              {{- end }}
              path: {{ .Values.keycloak.path }}/health/live
            failureThreshold: 150
            initialDelaySeconds: 20
            periodSeconds: 2
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              {{- if and .Values.tls.enabled .Values.keycloak.tlsSecretName }}
              scheme: HTTPS
              port: https
              {{- else }}
              scheme: HTTP
              port: http
              {{- end }}
              path: {{ .Values.keycloak.path }}/health/ready
            failureThreshold: 250
            initialDelaySeconds: 20
            periodSeconds: 2
            successThreshold: 1
            timeoutSeconds: 1
      {{- if .Values.keycloak.privateRepoEnabled }}
      imagePullSecrets:
        - name: image-credentials
      {{- end }}
      volumes:
        {{- if and .Values.tls.enabled .Values.keycloak.tlsSecretName }}
        - name: keycloak-tls-certificates
          secret:
            defaultMode: 420
            optional: false
            secretName: {{ .Values.keycloak.tlsSecretName }}
        {{- end }}
        - name: realm-config
          configMap:
            name: {{ .Values.keycloak.configmapName }}
