{{- if not .Values.keycloakSecret  }} #this value is not mentioned in any values file
---
apiVersion: batch/v1
kind: Job
metadata:
  name: create-secret-keycloak-initial-admin
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 5
  template:
    spec:
      serviceAccountName: default1
      containers:
      - name: create-secret-keycloak-initial-admin
        image: bitnami/kubectl:latest
        command: ["/bin/sh", "-c"]
        args:
        - |
          set -e
          # Wait for the postgres secret to be ready
          while [ "$(kubectl get secret postgres -n {{ .Release.Namespace }} -o jsonpath='{.data}')" == "" ]; do
            echo "Waiting for postgres secret..."
            sleep 5
          done
          # Extracting admin password from postgres secret
          ADMIN_PASSWORD=$(kubectl get secret postgres -n default -o jsonpath='{.data.adminPwd}' | base64 --decode)
          echo "$ADMIN_PASSWORD"
          # Create the keycloak-initial-admin secret
          kubectl create secret generic {{ .Values.serviceName }}-initial-admin --from-literal=username="{{ .Values.adminUsername }}" --from-literal=password="$ADMIN_PASSWORD"
      restartPolicy: OnFailure

{{- end }}