{{- if not .Values.keycloakSecret  }} #this value is not mentioned in any values file
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.serviceName }}-initial-admin
  namespace: {{ .Release.Namespace }}
data:
  {{- $secretData := get (lookup "v1" "Secret" .Release.Namespace (print .Values.serviceName "-initial-admin")) "data" | default dict }}
  username: "{{ (get $secretData "username" | b64dec) | default .Values.adminUsername | b64enc }}"
  password: "{{ (get $secretData "password" | b64dec) | default .Values.adminPassword | default (randAscii 32) | b64enc }}"
type: Opaque
{{- end }}