{{- if .Values.OpenNMS.minionCertificateManager.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.OpenNMS.minionCertificateManager.serviceName }}
  labels:
    app: {{ .Values.OpenNMS.minionCertificateManager.serviceName }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.OpenNMS.minionCertificateManager.serviceName }}
  strategy:
    type: Recreate
  replicas: {{ .Values.OpenNMS.minionCertificateManager.replicas }}
  template:
    metadata:
      labels:
        appdomain: opennms
        app: {{ .Values.OpenNMS.minionCertificateManager.serviceName }}
      annotations:
        # roll the deployment when the Spring boot environment variable configmap changes
        checksum/spring-boot-env-configmap: {{ include (print $.Template.BasePath "/opennms/spring-boot-env-configmap.yaml") . | sha256sum }}
        kubectl.kubernetes.io/default-container: "{{ .Values.OpenNMS.minionCertificateManager.serviceName }}"
    spec:
      {{- if .Values.nodeRestrictions.enabled }}
      nodeSelector:                                                                                    
        {{ .Values.nodeRestrictions.key }}: {{ .Values.nodeRestrictions.value }}                       
      tolerations:
        - effect: "NoSchedule"                                                                         
          key: "{{ .Values.nodeRestrictions.key }}"                                                    
          operator: "Equal"
          value: {{ .Values.nodeRestrictions.value }} 
      affinity: 
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:                                             
          - weight: 1                                                                                  
            preference:                                                                                
              matchExpressions:                                                                        
              - key: "{{ .Values.nodeRestrictions.key }}"                                              
                operator: In
                values:                                                                                
                - {{ .Values.nodeRestrictions.value }}                                                 
      {{- end }}
      volumes:
        - name: certificate-secrets
          secret:
            secretName: {{ .Values.OpenNMS.minionCertificateManager.caSecretName }}
        - name: minion-certificate-manager-secrets
          secret:
            secretName: {{ .Values.OpenNMS.minionCertificateManager.mtlsSecretName }}
        - name: spring-boot-app-config-volume
          configMap:
            name: spring-boot-app-config
        - name: rocksdb
          persistentVolumeClaim:
            claimName: minion-certificate-manager-pvc
      containers:
        - name: {{ .Values.OpenNMS.minionCertificateManager.serviceName }}
          image: {{ include "lokahi.image" (dict "Values" .Values "thisService" .Values.OpenNMS.minionCertificateManager) | quote }}
          imagePullPolicy: {{ .Values.OpenNMS.minionCertificateManager.imagePullPolicy }}
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-XX:MaxRAMPercentage=50 -javaagent:agent/opentelemetry-javaagent.jar -agentlib:jdwp=transport=dt_socket,server=y,address=5005,suspend=n,quiet=y"  # FIXME: Permanent debug port, enable only for dev mode
            - name: KEYCLOAK_BASE_URL
              value: "http://{{ .Values.keycloak.serviceName }}:8080/auth/"
            - name: KEYCLOAK_REALM
              value: "{{ .Values.keycloak.realmName }}"
            - name: GRPC_SERVER_PORT
              value: "8990"
            # Do not put any env variables below this. The lokahi.development.env include should be last
            # in the 'env' section so variables can be overridden with Helm chart values when needed.
            {{- include "lokahi.deployment.env" (dict "Values" .Values "thisService" .Values.OpenNMS.minionCertificateManager) | nindent 12 }}
          envFrom:
          - configMapRef:
              name: spring-boot-env
          ports:
            - name: grpc
              containerPort: 8990
          volumeMounts:
            - name: certificate-secrets
              mountPath: "/run/secrets/certificates"
              readOnly: true
            - name: minion-certificate-manager-secrets
              mountPath: "/run/secrets/mtls"
              readOnly: true
            - name: spring-boot-app-config-volume
              mountPath: "/app/config"
            - name: rocksdb
              mountPath: "/app/rocks-db"
          resources:
            limits:
              cpu: "{{ .Values.OpenNMS.minionCertificateManager.resources.limits.cpu }}"
              memory: "{{ .Values.OpenNMS.minionCertificateManager.resources.limits.memory }}"
            requests:
              cpu: "{{ .Values.OpenNMS.minionCertificateManager.resources.requests.cpu }}"
              memory: "{{ .Values.OpenNMS.minionCertificateManager.resources.requests.memory }}"
      {{- if .Values.OpenNMS.minionCertificateManager.privateRepoEnabled }}
      imagePullSecrets:
        - name: image-credentials
      {{- end }}

{{- end }}
