{{- if .Values.OpenNMS.minionCertificateManager.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: minion-certificate-manager-pvc
  labels:
    app: {{ .Values.OpenNMS.minionCertificateManager.serviceName }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.OpenNMS.minionCertificateManager.volumeSize }}
{{- end }}
