{{- if .Values.OpenNMS.minionCertificateManager.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.OpenNMS.minionCertificateManager.serviceName }}
  labels:
    app: {{ .Values.OpenNMS.minionCertificateManager.serviceName }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.OpenNMS.port.grpc | default 8990 }}
      protocol: TCP
      name: grpc
  selector:
    app: {{ .Values.OpenNMS.minionCertificateManager.serviceName }}
{{- end }}
