apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.OpenNMS.dataChoices.serviceName }}
  labels:
    app: {{ .Values.OpenNMS.dataChoices.serviceName }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.OpenNMS.dataChoices.serviceName }}
  replicas: {{ .Values.OpenNMS.dataChoices.replicas }}
  template:
    metadata:
      labels:
        appdomain: opennms
        app: {{ .Values.OpenNMS.dataChoices.serviceName }}
      annotations:
        # roll the deployment when the Spring boot environment variable configmap changes
        checksum/spring-boot-env-configmap: {{ include (print $.Template.BasePath "/opennms/spring-boot-env-configmap.yaml") . | sha256sum }}
        kubectl.kubernetes.io/default-container: "{{ .Values.OpenNMS.dataChoices.serviceName }}"
    spec:
      {{- if .Values.nodeRestrictions.enabled }}
      nodeSelector:                                                                                    
        {{ .Values.nodeRestrictions.key }}: {{ .Values.nodeRestrictions.value }}                       
      tolerations:
        - effect: "NoSchedule"                                                                         
          key: "{{ .Values.nodeRestrictions.key }}"                                                    
          operator: "Equal"
          value: {{ .Values.nodeRestrictions.value }} 
      affinity: 
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:                                             
          - weight: 1                                                                                  
            preference:                                                                                
              matchExpressions:                                                                        
              - key: "{{ .Values.nodeRestrictions.key }}"                                              
                operator: In
                values:                                                                                
                - {{ .Values.nodeRestrictions.value }}                                                 
      {{- end }}
      volumes:
        - name: spring-boot-app-config-volume
          configMap:
            name: spring-boot-app-config
      {{- if .Values.Citus.enabled }}
      initContainers:
        - name: wait-for-db
          image: postgres:16-alpine
          args:
          - /bin/sh
          - -c
          - | 
            set -x;
            while ! psql -U {{ .Values.global.citus.adminUser | default .Values.Citus.adminUser }} -d {{ .Values.global.citus.databaseName | default .Values.OpenNMS.dataChoices.databaseName }} -h {{ .Values.OpenNMS.dataChoices.databaseHost }} -p {{  .Values.global.citus.port | default .Values.Citus.port }} -c 'select 1'; do
              echo "Waiting for DB to be available"
              sleep 10
            done
            echo "Database is available"
      {{- end }}
      containers:
        - name: {{ .Values.OpenNMS.dataChoices.serviceName }}
          image: {{ include "lokahi.image" (dict "Values" .Values "thisService" .Values.OpenNMS.dataChoices "tag" .Chart.AppVersion) }}
          imagePullPolicy: {{ .Values.OpenNMS.dataChoices.imagePullPolicy }}
          env:
            - name: JAVA_TOOL_OPTIONS
              {{- if .Values.OpenNMS.dataChoices.debug.enabled }}
              value: "{{- if .Values.OpenNMS.dataChoices.debug.java.preferIPv4Stack }} -Djava.net.preferIPv4Stack=true {{ end }} -javaagent:{{ .Values.OpenNMS.dataChoices.debug.java.javaAgentPath }} -agentlib:jdwp=transport={{ .Values.OpenNMS.dataChoices.debug.transport }},server={{ if .Values.OpenNMS.dataChoices.debug.server }}y{{ else }}n{{ end }},address={{ .Values.OpenNMS.dataChoices.debug.port }},suspend={{ if .Values.OpenNMS.dataChoices.debug.suspend }}y{{ else }}n{{ end }},quiet={{ if .Values.OpenNMS.dataChoices.debug.quiet }}y{{ else }}n{{ end }}"
              {{- else }}
              value: "{{- if .Values.OpenNMS.dataChoices.debug.java.preferIPv4Stack }} -Djava.net.preferIPv4Stack=true {{ end }} -javaagent:{{ .Values.OpenNMS.dataChoices.debug.java.javaAgentPath }}"
              {{- end }} 
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://{{ .Values.OpenNMS.dataChoices.databaseHost }}:{{ .Values.global.citus.port | default .Values.Citus.port }}/{{ .Values.global.citus.databaseName | default .Values.OpenNMS.dataChoices.databaseName }}?currentSchema={{ .Values.OpenNMS.dataChoices.databaseSchemaName }}"
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: dataChoicesUsr
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: dataChoicesPwd
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "{{ .Values.global.kafkaClient.bootstrapServers }}"
            - name: KEYCLOAK_BASE_URL
              value: "http://{{ .Values.Keycloak.serviceName }}:{{ .Values.global.keycloakPort | default .Values.Keycloak.port }}{{ .Values.Keycloak.path }}/"
            - name: KEYCLOAK_REALM
              value: "{{ .Values.Keycloak.realmName }}"
            - name: GRPC_SERVER_PORT
              value: "{{ .Values.OpenNMS.port.grpc | default 6565 }}"
            # Do not put any env variables below this. The lokahi.development.env include should be last
            # in the 'env' section so variables can be overridden with Helm chart values when needed.
            {{- include "lokahi.deployment.env" (dict "Values" .Values "thisService" .Values.OpenNMS.dataChoices "tag" .Chart.AppVersion) | nindent 12 }}
          envFrom:
          - configMapRef:
              name: spring-boot-env
          ports:
            - name: http
              containerPort: 8080
            - name: grpc
              containerPort: {{ .Values.OpenNMS.port.grpc | default 6565 }} 
          volumeMounts:
            - name: spring-boot-app-config-volume
              mountPath: "/app/config"
          livenessProbe:
            httpGet:
              path: "/actuator/health/liveness"
              port: http
              scheme: HTTP
            initialDelaySeconds: 20
            timeoutSeconds: 1
            periodSeconds: 2
            successThreshold: 1
            failureThreshold: 150
          readinessProbe:
            httpGet:
              path: "/actuator/health/readiness"
              port: http
              scheme: HTTP
            initialDelaySeconds: 20
            timeoutSeconds: 1
            periodSeconds: 2
            successThreshold: 1
            failureThreshold: 250
          resources:
            limits:
              cpu: "{{ .Values.OpenNMS.dataChoices.resources.limits.cpu }}"
              memory: "{{ .Values.OpenNMS.dataChoices.resources.limits.memory }}"
            requests:
              cpu: "{{ .Values.OpenNMS.dataChoices.resources.requests.cpu }}"
              memory: "{{ .Values.OpenNMS.dataChoices.resources.requests.memory }}"
      {{- if .Values.OpenNMS.dataChoices.privateRepoEnabled }}
      imagePullSecrets:
        - name: image-credentials
      {{- end }}
