{{- if .Values.mailServer.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mailServer.serviceName }}
  labels:
    app: {{ .Values.mailServer.serviceName }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.mailServer.port }}
      protocol: TCP
      name: http
    - port: {{ .Values.mailServer.smtpPort }}
      protocol: TCP
      name: smtp
  selector:
    app: {{ .Values.mailServer.serviceName }}
{{- end }}
