
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ .Values.serviceName }}
  name: cortex-config-webhook
  namespace: {{ .Release.Namespace }}
data:
  webhook-conf.yml: |
    template_files:
      default_template: |
        {{ define "__alertmanager" }}AlertManager{{ end }}
        {{ define "__alertmanagerURL" }}{{ .ExternalURL }}/#/alerts?receiver={{ .Receiver | urlquery }}{{ end }}    
    alertmanager_config: |
      global:
      route:
        group_wait: 30s
        group_interval: 1m
        receiver: webhook_receiver
      receivers:
        - name: webhook_receiver
          webhook_configs:
          - url: "http://{{ .Values.metricsthresholdprocessor.serviceName }}:{{ .Values.metricsthresholdprocessor.port }}/webhook/metrics-threshold"