{{ if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.serviceName }}
  name: {{ .Values.serviceName }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.port }}
      protocol: TCP
      targetPort: 9000
      name: cortex-http
  selector:
    app: {{ .Values.serviceName }}
{{ end }}
