apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.OpenNMS.api.serviceName }}
  name: {{ .Values.OpenNMS.api.serviceName }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: {{ .Values.OpenNMS.port.grpc | default 9090 }}
      protocol: TCP
      name: grpc
  selector:
    app: {{ .Values.OpenNMS.api.serviceName }}
  type: NodePort
