{{- if .Values.ingress.enabled }}
{{/*FIXME Is this even used?*/}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opennms-nginx-errors
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: opennms-nginx-errors
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: opennms-nginx-errors
  template:
    metadata:
      labels:
        appdomain: opennms
        app.kubernetes.io/name: opennms-nginx-errors
      annotations:
        kubectl.kubernetes.io/default-container: "opennms-nginx-error-server"
    spec:
      {{- if .Values.nodeRestrictions.enabled }}
      nodeSelector:                                                                                    
        {{ .Values.nodeRestrictions.key }}: {{ .Values.nodeRestrictions.value }}                       
      tolerations:
        - effect: "NoSchedule"                                                                         
          key: "{{ .Values.nodeRestrictions.key }}"                                                    
          operator: "Equal"
          value: {{ .Values.nodeRestrictions.value }} 
      affinity: 
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:                                             
          - weight: 1                                                                                  
            preference:                                                                                
              matchExpressions:                                                                        
              - key: "{{ .Values.nodeRestrictions.key }}"                                              
                operator: In
                values:                                                                                
                - {{ .Values.nodeRestrictions.value }}                                                 
      {{- end }}
      containers:
        - name: opennms-nginx-error-server
          image: {{ .Values.customErrors.image }}
          ports:
            - containerPort: 8080
          env:
            - name: DEBUG
              value: "{{ .Values.customErrors.debug }}"
{{- end }}
