{{- if .Values.ingress.enabled }}
# Source: ingress-nginx/templates/controller-service.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: controller-{{ .Release.Namespace }}
    app.kubernetes.io/name: ingress-nginx-{{ .Release.Namespace }}
    app.kubernetes.io/instance: ingress-nginx-{{ .Release.Namespace }}
    app.kubernetes.io/part-of: ingress-nginx-{{ .Release.Namespace }}
    app.kubernetes.io/version: 1.3.0
  name: ingress-grpc-nginx-controller
  namespace: {{ .Release.Namespace }}
spec:
  type: NodePort
  ports:
    - name: grpc
      protocol: TCP
      nodePort: 30990
      port: 8990
  selector:
    app.kubernetes.io/component: controller-{{ .Release.Namespace }}
    app.kubernetes.io/name: ingress-nginx-{{ .Release.Namespace }}
    app.kubernetes.io/instance: ingress-nginx-{{ .Release.Namespace }}
{{- end }}
