{{- if .Values.ingress.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/component: controller-{{ .Release.Namespace }}
    app.kubernetes.io/name: ingress-nginx-{{ .Release.Namespace }}
    app.kubernetes.io/instance: ingress-nginx-{{ .Release.Namespace }}
    app.kubernetes.io/part-of: ingress-nginx-{{ .Release.Namespace }}
    app.kubernetes.io/version: 1.3.0
  name: ingress-nginx-{{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ingress-nginx-{{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: ingress-nginx
    namespace: {{ .Release.Namespace }}
{{- end }}
