apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.OpenNMS.minionCertificateVerifier.serviceName }}
  labels:
    app: {{ .Values.OpenNMS.minionCertificateVerifier.serviceName }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.OpenNMS.minionCertificateVerifier.serviceName }}
