{{ if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka
  name: {{ .Values.serviceName }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: {{ .Values.port }}
      name: client
      protocol: TCP
      targetPort: {{ .Values.port }}
    - port: {{ .Values.controllerPort }}
      name: controller
      protocol: TCP
      targetPort: {{ .Values.controllerPort }}
  selector:
    app: {{ .Values.serviceName }}
  type: ClusterIP
{{ end }}
