apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.OpenNMS.alert.serviceName }}
  labels:
    app: {{ .Values.OpenNMS.alert.serviceName }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.OpenNMS.port.http | default 8080 }}
      protocol: TCP
      name: http
    - port: {{ .Values.OpenNMS.port.grpc | default 6565 }}
      protocol: TCP
      name: grpc
  selector:
    app: {{ .Values.OpenNMS.alert.serviceName }}
