{{- if .Values.ingress.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ingress-nginx-admission-{{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: admission-webhook-{{ .Release.Namespace }}
    app.kubernetes.io/name: ingress-nginx-{{ .Release.Namespace }}
    app.kubernetes.io/instance: ingress-nginx-{{ .Release.Namespace }}
    app.kubernetes.io/part-of: ingress-nginx-{{ .Release.Namespace }}
    app.kubernetes.io/version: 1.3.0
rules:
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - validatingwebhookconfigurations
  verbs:
  - get
  - update
{{- end }}
