{{- if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
  labels:
    app: {{ .Values.serviceName }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: {{ .Values.grafanaPort }}
      protocol: TCP
      targetPort: 3000
  selector:
    app: {{ .Values.serviceName }}
  type: ClusterIP
{{- end }}
