name: Release Helm Charts

on:
 push:
  branches:
     - master

# Make sure only one copy of this workflow can run at a time.
concurrency: ${{ github.workflow }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: install dependencies Git
        run: |
          cd lokahi
          helm dependency build

      - name: Run chart-releaser - Lokahi and Minion
        uses: helm/chart-releaser-action@v1.5.0
        with:
          charts_dir: .
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      # Disable for now -- we need to figureout a better way to handle this
      #- name: Run chart-releaser - Dependencies
      #  uses: helm/chart-releaser-action@v1.5.0
      #  with:
      #    charts_dir: dependencies
      #  env:
      #    CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

